namespace HomeControl.Source.ViewModel.Games;

public static class WordList {
    public static readonly List<string> PictionaryEasyList = new() {
        "Earth",
        "Christmas",
        "Mickey Mouse",
        "Above",
        "Alive",
        "Alligator",
        "Animal",
        "Ankle",
        "Answer",
        "Ants",
        "Apple",
        "Arm",
        "Awake",
        "Baby",
        "Backpack",
        "Bag",
        "Bald",
        "Ball",
        "Balloon",
        "Banana",
        "Bark",
        "Baseball",
        "Basketball",
        "Bat",
        "Bath",
        "Bathroom",
        "Beach",
        "Beak",
        "Bear",
        "Bed",
        "Bell",
        "Bench",
        "Bike",
        "Bird",
        "Blanket",
        "Blocks",
        "Boat",
        "Bone",
        "Book",
        "Bounce",
        "Bow",
        "Bowl",
        "Box",
        "Boy",
        "Bracelet",
        "Brake",
        "Branch",
        "Bread",
        "Breakfast",
        "Bridge",
        "Broken",
        "Broom",
        "Bubble",
        "Bug",
        "Bumblebee",
        "Bunk Bed",
        "Bunny",
        "Bus",
        "Butterfly",
        "Button",
        "Buzz",
        "Cafeteria",
        "Camera",
        "Candle",
        "Car",
        "Carrot",
        "Cash",
        "Cat",
        "Caterpillar",
        "Cave",
        "Chair",
        "Cheerleader",
        "Cheese",
        "Chef",
        "Cherry",
        "Chicken",
        "Chimney",
        "Circle",
        "Clock",
        "Cloud",
        "Coat",
        "Coin",
        "Comb",
        "Computer",
        "Cone",
        "Cookie",
        "Corn",
        "Cow",
        "Cowboy",
        "Crab",
        "Crack",
        "Crayon",
        "Cube",
        "Cup",
        "Cupcake",
        "Curl",
        "Dad",
        "Desk",
        "Diamond",
        "Dinner",
        "Dinosaur",
        "Doctor",
        "Dog",
        "Doll",
        "Door",
        "Down",
        "Dragon",
        "Draw",
        "Dream",
        "Drum",
        "Duck",
        "Ear",
        "Ears",
        "Egg",
        "Elephant",
        "Elevator",
        "Eye",
        "Eyes",
        "Face",
        "Fact",
        "Fairy",
        "Feather",
        "Feet",
        "Finger",
        "Fire",
        "Fire Hydrant",
        "First",
        "Fish",
        "Flag",
        "Float",
        "Flower",
        "Fly",
        "Fog",
        "Football",
        "Fork",
        "Fountain",
        "Front",
        "Frown",
        "Frying Pan",
        "Fur",
        "Ghost",
        "Giraffe",
        "Girl",
        "Glasses",
        "Grandchild",
        "Grapes",
        "Grass",
        "Green",
        "Gym",
        "Hail",
        "Hair",
        "Hamburger",
        "Hand",
        "Hat",
        "Head",
        "Heart",
        "Heavy",
        "Helicopter",
        "Hello",
        "Help",
        "Hide-and-seek",
        "High",
        "Hippo",
        "Homework",
        "Hoof",
        "Hook",
        "Horn",
        "House",
        "Hungry",
        "Ice Cream",
        "Ice Cream Cone",
        "Inchworm",
        "Iron",
        "Island",
        "Jacket",
        "Jail",
        "Jar",
        "Jellyfish",
        "Key",
        "Kick",
        "King",
        "Kite",
        "Kitten",
        "Knee",
        "Ladybug",
        "Lamp",
        "Laugh",
        "Leaf",
        "Leg",
        "Legs",
        "Lemon",
        "Library",
        "Light",
        "Light Bulb",
        "Line",
        "Lion",
        "Lips",
        "Lizard",
        "Lollipop",
        "Long",
        "Loud",
        "Love",
        "Mailman",
        "Makeup",
        "Man",
        "Milk",
        "Mitten",
        "Mom",
        "Monkey",
        "Monster",
        "Moon",
        "Motorcycle",
        "Mountain",
        "Mountains",
        "Mouse",
        "Mouth",
        "Movie",
        "Music",
        "Nail",
        "Nail Polish",
        "Neck",
        "Nephew",
        "Night",
        "Nose",
        "Ocean",
        "Octopus",
        "Oink",
        "Opposite",
        "Orange",
        "Oval",
        "Owl",
        "Page",
        "Paint",
        "Pantry",
        "Pants",
        "Peas",
        "Pen",
        "Pencil",
        "Person",
        "Picnic",
        "Picture",
        "Pie",
        "Pig",
        "Pillow",
        "Pizza",
        "Plant",
        "Play",
        "Poem",
        "Popsicle",
        "Prince",
        "Princess",
        "Purse",
        "Push",
        "Rabbit",
        "Rain",
        "Ranch",
        "Red",
        "Refrigerator",
        "Relax",
        "Restaurant",
        "Right",
        "Ring",
        "River",
        "Robot",
        "Rock",
        "Rocket",
        "Room",
        "Sailboat",
        "Sandcastle",
        "School",
        "School Bus",
        "Scientist",
        "Scissors",
        "Scooter",
        "Sea Turtle",
        "Seashell",
        "Seek",
        "Shadow",
        "Sheep",
        "Ship",
        "Shirt",
        "Shoe",
        "Shopping",
        "Shovel",
        "Sick",
        "Singer",
        "Sister",
        "Skateboard",
        "Slide",
        "Smile",
        "Smoke",
        "Snail",
        "Snake",
        "Sneeze",
        "Snowflake",
        "Snowman",
        "Sock",
        "Socks",
        "Spider",
        "Spider Web",
        "Spool",
        "Spoon",
        "Spy",
        "Square",
        "Stairs",
        "Stamp",
        "Star",
        "Starfish",
        "State",
        "Storm",
        "Street",
        "Strong",
        "Suitcase",
        "Sun",
        "Sunglasses",
        "Swimming Pool",
        "Swimsuit",
        "Swing",
        "Table",
        "Tail",
        "Teeth",
        "Telephone",
        "Thunder",
        "Tired",
        "Tissue",
        "Toast",
        "Toothbrush",
        "Towel",
        "Town",
        "Train",
        "Trash Can",
        "Tree",
        "Triangle",
        "Turtle",
        "Uncle",
        "Unicorn",
        "Up",
        "Vacation",
        "Vet",
        "Video Camera",
        "Wallet",
        "Watch",
        "Water",
        "Weak",
        "Whale",
        "Wheel",
        "Whisper",
        "Window",
        "Witch",
        "Wolf",
        "Woman",
        "Worm",
        "Yellow",
        "Zebra",
        "Zero",
        "Zigzag"
    };

    public static readonly List<string> PictionaryMediumList = new() {
        "Friday",
        "Jupiter",
        "Segway",
        "Acne",
        "Aircraft",
        "Anvil",
        "Aquarium",
        "Art",
        "Artist",
        "Ask",
        "Aunt",
        "Baby",
        "Back",
        "Bag",
        "Bagel",
        "Bagpipe",
        "Banana Peel",
        "Banana",
        "Bandage",
        "Barn",
        "Baseboards",
        "Bat",
        "Batteries",
        "Battery",
        "Beach",
        "Beaver",
        "Birthday",
        "Birthday Cake",
        "Blackboard",
        "Blanket",
        "Blowfish",
        "Blue Jeans",
        "Blueprint",
        "Blush",
        "Bobsled",
        "Bowtie",
        "Box",
        "Braid",
        "Breakfast",
        "Brick",
        "Bruise",
        "Budget",
        "Bus",
        "Bushes",
        "Cage",
        "Calendar",
        "Campfire",
        "Canoe",
        "Cardboard",
        "Carpet",
        "Cartoon",
        "Cash",
        "Chalk",
        "Chameleon",
        "Chart",
        "Check",
        "Cheek",
        "Cheer",
        "Cheerleader",
        "Cheeseburger",
        "Children",
        "Chin",
        "Chips",
        "City",
        "Classroom",
        "Closed",
        "Coach",
        "Coat",
        "Cobra",
        "Cocoon",
        "Coil",
        "Coin",
        "Collar",
        "College",
        "Compass",
        "Computer",
        "Corn",
        "Corn Dog",
        "Cover",
        "Cowboy",
        "Coyote",
        "Cracker",
        "Crib",
        "Crumb",
        "Crust",
        "Cucumber",
        "Curb",
        "Curtains",
        "Curve",
        "Dad",
        "Daddy Longlegs",
        "Dance",
        "Deep",
        "Deer",
        "Delay",
        "Departure",
        "Desk",
        "Dew",
        "Dirt",
        "Dock",
        "Doctor",
        "Doghouse",
        "Dollar",
        "Door",
        "Doormat",
        "Drill",
        "Dump Truck",
        "Easel",
        "Eclipse",
        "Eel",
        "Electrical Outlet",
        "Electricity",
        "Elevator",
        "Elf",
        "Enter",
        "Equator",
        "Eraser",
        "Extension Cord",
        "Factory",
        "Family",
        "Faucet",
        "Fax",
        "Feast",
        "Ferry",
        "Firefighter",
        "Fishing Pole",
        "Fist",
        "Flagpole",
        "Flamingo",
        "Flood",
        "Foe",
        "Food",
        "Forehead",
        "Forest",
        "Free",
        "French Fries",
        "Front Porch",
        "Fruit",
        "Funny",
        "Gap",
        "Garbage Truck",
        "Gate",
        "Germ",
        "Giant",
        "Gingerbread Man",
        "Go",
        "Goat",
        "Goblin",
        "Goldfish",
        "Grandma",
        "Grape",
        "Growl",
        "Gum",
        "Hail",
        "Hair",
        "Hairbrush",
        "Half",
        "Hammer",
        "Happy",
        "Healthy",
        "Heel",
        "Hero",
        "Hip",
        "Home Movies",
        "Horse",
        "Hospital",
        "Hot Tub",
        "Hot-air Balloon",
        "Howl",
        "Hunter",
        "Hurricane",
        "Insect",
        "Ironing Board",
        "Island",
        "Jaw",
        "Jump",
        "Jungle",
        "Kayak",
        "Kettle",
        "Kiss",
        "Knot",
        "Latitude",
        "Lemon",
        "Lifejacket",
        "Lighthouse",
        "Lightsaber",
        "Liquid",
        "Locket",
        "Low",
        "Lung",
        "Magic Carpet",
        "Magnet",
        "Mail",
        "Mailman",
        "Map",
        "Marker",
        "Marshmallow",
        "Mine",
        "Minivan",
        "Mirror",
        "Mitten",
        "Monkey",
        "Morning",
        "Mountain Biking",
        "Mouth",
        "Movie Theater",
        "Mud",
        "Museum",
        "Mushroom",
        "Music",
        "Nail",
        "Napkin",
        "Narwhal",
        "Nature",
        "Needle",
        "Neon",
        "Net",
        "Newspaper",
        "Notepad",
        "Nurse",
        "Nut",
        "Oar",
        "Observe",
        "Oil",
        "Onion",
        "Open",
        "Page",
        "Paint",
        "Pajamas",
        "Panda",
        "Pantry",
        "Park",
        "Paw",
        "Peach",
        "Peanut",
        "Peck",
        "Pendulum",
        "Photograph",
        "Photographer",
        "Piano",
        "Pie",
        "Pigpen",
        "Pillowcase",
        "Pine Tree",
        "Pineapple",
        "Pinecone",
        "Ping Pong",
        "Pipe",
        "Piranha",
        "Pirate",
        "Plant",
        "Platypus",
        "Playground",
        "Pocket",
        "Pool",
        "Porch",
        "Pot",
        "Present",
        "Pretzel",
        "Princess",
        "Printer",
        "Prize",
        "Pulley",
        "Puppet",
        "Puzzle",
        "Quadruplets",
        "Radish",
        "Railroad",
        "Rainbow",
        "Rake",
        "Rat",
        "Rattle",
        "Recycle",
        "Refrigerator",
        "Reindeer",
        "Restaurant",
        "Rhinoceros",
        "Rib",
        "Ribbon",
        "Road Trip",
        "Robin",
        "Rocking Chair",
        "Roller Blading",
        "Room",
        "Root",
        "Rowboat",
        "Rug",
        "Run",
        "Salt and Pepper",
        "Sandpaper",
        "Sap",
        "Saxophone",
        "Scale",
        "Scar",
        "Scarf",
        "School",
        "Screwdriver",
        "Sea Turtle",
        "Seahorse",
        "Seal",
        "Seashell",
        "See",
        "Sense",
        "Shadow",
        "Shark",
        "Shed",
        "Shelf",
        "Shopping Cart",
        "Shovel",
        "Sidekick",
        "Skateboard",
        "Ski",
        "Skirt",
        "Sleeve",
        "Slide",
        "Slope",
        "Smog",
        "Snap",
        "Sneeze",
        "Snowball",
        "Snowboard",
        "Snowboarding",
        "Snowflake",
        "Snuggle",
        "Soccer",
        "Soil",
        "Solar System",
        "Spear",
        "Sponge",
        "Spool",
        "Spoon",
        "Squirrel",
        "Squirt Gun",
        "Stage",
        "Stain",
        "Start",
        "Stem",
        "Stepmom",
        "Stomach",
        "Stomp",
        "Stoplight",
        "Stork",
        "Storm",
        "Stove",
        "Strawberry",
        "String",
        "Stump",
        "Subway",
        "Suitcase",
        "Sunflower",
        "Sunglasses",
        "Surfboard",
        "Swimming Pool",
        "Swing",
        "Sword",
        "T-shirt",
        "Table",
        "Tadpole",
        "Tag",
        "Tar",
        "Taxi",
        "Team",
        "Teammate",
        "Teenager",
        "Tennis Shoes",
        "Tent",
        "Thief",
        "Third Plate",
        "Throat",
        "Throne",
        "Ticket",
        "Tightrope",
        "Time",
        "Timer",
        "Tip",
        "Toaster",
        "Toilet Paper",
        "Tongs",
        "Towel",
        "Tractor",
        "Trampoline",
        "Trap",
        "Treasure",
        "Truck",
        "Trumpet",
        "Tuba",
        "Tulip",
        "Unicycle",
        "Unite",
        "Usher",
        "Vegetable",
        "Verse",
        "Vest",
        "Video Camera",
        "Volunteer",
        "Want",
        "Waste",
        "Watchtower",
        "Waterfall",
        "Watering Can",
        "Wedge",
        "Week",
        "Weight",
        "Well",
        "Wind",
        "Window",
        "Windshield",
        "Wood",
        "Worm",
        "Wreck",
        "Wrist",
        "Writer",
        "Yo-yo",
        "Zebra",
        "Zoo"
    };

    public static readonly List<string> PictionaryHardList = new() {
        "Bff",
        "Cd",
        "Heinz 57",
        "Internet",
        "Zen",
        "Abrasive",
        "Accounting",
        "Advertising",
        "Agenda",
        "Airport Security",
        "Airway",
        "Amusement Park",
        "Apathetic",
        "Applause",
        "Art Gallery",
        "Ashamed",
        "Athlete",
        "Avocado",
        "Baby-sitter",
        "Baguette",
        "Barber",
        "Bargain",
        "Baseboards",
        "Bedbug",
        "Beluga Whale",
        "Birthday",
        "Biscuit",
        "Blizzard",
        "Blossom",
        "Blueprint",
        "Blush",
        "Boa Constrictor",
        "Bonnet",
        "Bookend",
        "Booth",
        "Brand",
        "Bruise",
        "Buddy",
        "Captain",
        "Carat",
        "Cardboard",
        "Cargo",
        "Carnival",
        "Cartoon",
        "Catalog",
        "Ceiling Fan",
        "Cellar",
        "Chameleon",
        "Character",
        "Cheat",
        "Cheerleader",
        "Chisel",
        "Clamp",
        "Classroom",
        "Clay",
        "Clique",
        "Cloak",
        "Clown",
        "Coastline",
        "Coil",
        "Comfy",
        "Commercial",
        "Compare",
        "Competition",
        "Connection",
        "Costume",
        "Cot",
        "Country",
        "Cowboy",
        "Crate",
        "Cream",
        "Crime",
        "Crop Duster",
        "Crow's Nest",
        "Crust",
        "Cubicle",
        "Cuckoo Clock",
        "Cupola",
        "Cushion",
        "Customer",
        "Dance",
        "Date",
        "Dawn",
        "Dead End",
        "Degree",
        "Deliver",
        "Dentist",
        "Dew",
        "Dimple",
        "Disc Jockey",
        "Distance",
        "Diver",
        "Divine",
        "Dizzy",
        "Dodgeball",
        "Dorsal",
        "Drain",
        "Dream",
        "Dress Shirt",
        "Drip",
        "Dripping",
        "Earache",
        "Earthquake",
        "Edit",
        "Eighteen-wheeler",
        "Electrical Outlet",
        "Elf",
        "Elope",
        "Environment",
        "Eraser",
        "Exercise",
        "Fade",
        "Fast Food",
        "Fiddle",
        "Fireman Pole",
        "Fireside",
        "First Class",
        "Fizz",
        "Flannel",
        "Flavor",
        "Flu",
        "Flush",
        "Foam",
        "Forever",
        "Fortress",
        "Fourth Down",
        "Freshman",
        "Front",
        "Gas Station",
        "Geologist",
        "Germ",
        "Geyser",
        "Ginger",
        "Glue Stick",
        "Goalkeeper",
        "Goblin",
        "Gold Medal",
        "Government",
        "Gown",
        "Grandpa",
        "Grasslands",
        "Great-grandfather",
        "Grocery Store",
        "Guile",
        "Hairspray",
        "Hand Soap",
        "Hang Glider",
        "Headache",
        "Hearty",
        "Heater",
        "Hermit Crab",
        "Hipster",
        "Hole in One",
        "Hospital",
        "Hot Tub",
        "Houseboat",
        "Household",
        "Human",
        "Humidifier",
        "Humidity",
        "Hurdle",
        "Husband",
        "Hut",
        "Hydrogen",
        "Icicle",
        "Important",
        "Injury",
        "Inspect",
        "Interception",
        "Irritated",
        "Ivy",
        "Jade",
        "Jaw",
        "Jazz",
        "Jog",
        "Judge",
        "Juggle",
        "Jungle",
        "Junk",
        "Knight",
        "Lace",
        "Laminate",
        "Landlord",
        "Lap",
        "Laser",
        "Last",
        "Laundry Detergent",
        "Leak",
        "Learn",
        "Lend",
        "Letter Opener",
        "Light-year",
        "Living Room",
        "Loveseat",
        "Lullaby",
        "Lumberyard",
        "Lunch Tray",
        "Lung",
        "Macaroni",
        "Major League",
        "Manatee",
        "Mascot",
        "Mast",
        "Mayor",
        "Molar",
        "Movie",
        "Multiplication",
        "Musician",
        "Nanny",
        "Nap",
        "New",
        "Nightmare",
        "Oar",
        "Opponent",
        "Orbit",
        "Organ",
        "Owner",
        "Pail",
        "Pain",
        "Parade",
        "Parent",
        "Password",
        "Pawn",
        "Payment",
        "Pest",
        "Pharaoh",
        "Phonemics",
        "Pickup Truck",
        "Picture Frame",
        "Pigpen",
        "Pilot",
        "Pizza Sauce",
        "Plaid",
        "Plank",
        "Plantation",
        "Plow",
        "Plumber",
        "Pocket",
        "Poison",
        "Postcard",
        "Prey",
        "Prime Meridian",
        "Printer Ink",
        "Produce",
        "Professor",
        "Propose",
        "Publisher",
        "Punk",
        "Puppet",
        "Purge",
        "Purpose",
        "Putty",
        "Puzzle Piece",
        "Quicksand",
        "Quit",
        "Ratchet",
        "Reason",
        "Receipt",
        "Recess",
        "Record",
        "Reimbursement",
        "Religion",
        "Replace",
        "Research",
        "Resident",
        "Retail",
        "Reveal",
        "Riddle",
        "Rim",
        "Ringleader",
        "Roller Coaster",
        "Roommate",
        "Ruby",
        "Rut",
        "S'mores",
        "Saddle",
        "Safe",
        "Salmon",
        "Sash",
        "Scalawag",
        "Scar Tissue",
        "School",
        "Scoundrel",
        "Scuff Mark",
        "Scurvy",
        "Season",
        "Self",
        "Shack",
        "Shampoo",
        "Sheep Dog",
        "Shower Curtain",
        "Shrew",
        "Shrink Ray",
        "Signal",
        "Sip",
        "Skating Rink",
        "Ski Goggles",
        "Ski Lift",
        "Sled",
        "Smoldering",
        "Snooze",
        "Snore",
        "Snow Shoe",
        "Snowstorm",
        "Somersault",
        "Sow's Ear",
        "Space Shuttle",
        "Speakers",
        "Spite",
        "Spoil",
        "Sponge",
        "Sports Car",
        "Squeegee",
        "Stadium",
        "Stage",
        "Station Wagon",
        "Sticky Note",
        "Stockbroker",
        "Stow",
        "Stutter",
        "Sugar",
        "Sun Block",
        "Sunburn",
        "Surround",
        "Sushi",
        "Swamp",
        "Swarm",
        "Sweater",
        "Sweater Vest",
        "Swing Dancing",
        "Swirl",
        "Sword Swallower",
        "Tablespoon",
        "Taxes",
        "Taxi",
        "Taxidermist",
        "Team",
        "Tearful",
        "Teleconference",
        "Telephone Booth",
        "Tendency",
        "Terrify",
        "Testify",
        "Thaw",
        "Theorize",
        "Thief",
        "Think",
        "Through",
        "Ticket",
        "Tilt",
        "Time Machine",
        "Tin",
        "Tinting",
        "Tip",
        "Tiptoe",
        "Toddler",
        "Tow Truck",
        "Traffic Jam",
        "Trapped",
        "Trip",
        "Trombone",
        "Truck Stop",
        "Tugboat",
        "Turtleneck",
        "University",
        "Urgent",
        "Vacation",
        "Vanish",
        "Vein",
        "Vessel",
        "Violent",
        "Wag",
        "Water Buffalo",
        "Water Cycle",
        "Waver",
        "Wax",
        "Weather",
        "Wedding Cake",
        "Welder",
        "Whatever",
        "Wheelie",
        "Whisk",
        "Whole Milk",
        "Wind",
        "Wish",
        "Wool",
        "Wooly Mammoth",
        "World",
        "Wrap",
        "Wreath",
        "Yacht",
        "Yak",
        "Yard",
        "Yardstick",
        "Yodel",
        "Zigzag",
        "Zipper",
        "Zoom"
    };

    public static readonly List<string> PictionaryAdultList = new() {
        "69",
        "Baby Maker",
        "Bad Ass",
        "Blow Job",
        "Bondage",
        "Booty Call",
        "Cock",
        "Cow Girl",
        "Crack Head",
        "Deepthroat",
        "Doggy Style",
        "Gold Digger",
        "Grenade",
        "Happy Trail",
        "Hooker",
        "Lap Dance",
        "One Night Stand",
        "Second Base",
        "Sexting",
        "Swingers",
        "Threesome",
        "Twerk",
        "Vibrator"
    };

    public static readonly List<string> NhieQuestionList = new() {
        "wanted to be one of the Kardashians",
        "dressed as the opposite sex",
        "watched SpongeBob SquarePants",
        "cried during a Pixar movie",
        "had a crush, or a man crush, on Ron Swanson",
        "sung karaoke in public",
        "watched the \"Gangnam Style\" music video on repeat",
        "had a crush on someone from Full House",
        "watched an episode of Gilmore Girls",
        "pretended to know a stranger",
        "scared myself in a mirror",
        "missed a high five",
        "sang in the shower",
        "blamed farts on an animal",
        "wished I were a wizard at Hogwarts",
        "had a nightmare about zombies chasing me",
        "pretended to laugh at a joke I didn't get",
        "been scared of clowns",
        "been scared of spiders",
        "been scared of snakes",
        "been scared of the dark",
        "been scared of heights",
        "thought a cartoon character was hot",
        "faked being sick so I could play video games",
        "liked Star Wars more than Star Trek",
        "tried out to be an extra in a movie",
        "scored over 100 while bowling",
        "used an Instant Pot",
        "played over 100 levels of Candy Crush",
        "won a game of Scrabble",
        "won a game of Chess",
        "won a game of Monopoly",
        "made a duck face when taking a selfie",
        "been on a podcast",
        "daydreamed about being on a talk show and what I'd talk about",
        "Googled my own name to see what comes up",
        "pretended I was running from zombies while on a run",
        "sat in the shower",
        "tried something I saw on Pinterest",
        "downloaded a song from LimeWire",
        "ugly cried for no reason",
        "creeped on someone I just met on social media",
        "been out of the country",
        "re-gifted a gift card",
        "traveled out of state by myself",
        "flown in a helicopter",
        "been on stage in front of a crowd",
        "lied in a job interview",
        "stalked a crush",
        "sung karaoke",
        "agreed with something Donald Trump said",
        "thought about what type of dog I would be",
        "watched children's cartoons I'm too old for",
        "lost my phone while it was in my pocket",
        "locked my keys in my car",
        "not tipped at a restaurant",
        "given money to a homeless person",
        "looked at the sun during an eclipse",
        "bungee-jumped",
        "had surgery",
        "been committed to a mental hospital",
        "jumped out of a plane",
        "made a wish at a fountain",
        "eaten a bug on purpose",
        "cut someone in line",
        "stayed up all night",
        "read a spicy book",
        "read a Harry Potter book",
        "been inside of a library",
        "lied about my age",
        "shot a gun",
        "had a cavity",
        "been mini-golfing",
        "seen an elephant in real life",
        "been to Disney World",
        "bought clothing online",
        "had someone draw a caricature of me",
        "owned an Xbox 360",
        "owned an PlayStation 2",
        "\"gone down the YouTube rabbit hole\"",
        "seen the movie Titanic",
        "met a celebrity one on one",
        "thought a movie was better than the book",
        "voted",
        "owned an expensive \"designer\" watch",
        "ridden an electric skateboard",
        "learned how to play a musical instrument",
        "played in at least one foot of snow",
        "finished a Sudoku puzzle",
        "Googled something so I'd know how to spell it",
        "cheated on a test",
        "cried watching Homeward Bound",
        "licked a frozen pole",
        "had gum in my hair",
        "taken a horrible picture on picture day",
        "been a bully",
        "wanted to be a superhero",
        "been scared of the dark",
        "had trouble sleeping after watching a scary movie",
        "been to a sleepover this year",
        "cried at school this year",
        "sang on a stage",
        "performed in a talent show",
        "killed ants with a magnifying glass",
        "dropped Mentos into soda",
        "eaten something on a dare",
        "sucked my thumb today",
        "believed my toys had feelings",
        "watched Blue's Clues",
        "been terrified of a theme park ride",
        "been to a haunted house",
        "dressed up slutty on purpose for Halloween",
        "been suspended from school",
        "built a fort with blankets this year",
        "fallen off a dirt bike",
        "played video games for over 24 hours straight",
        "stolen money from a sibling",
        "had a bunk bed",
        "played the Pokémon card game",
        "been on a family road trip",
        "named a stuffed animal",
        "used training wheels",
        "eaten only candy for dinner",
        "stayed in character all day",
        "lied about being related to someone famous",
        "written notes on the desk to use during a test",
        "tried to sign a permission slip for my parents",
        "stolen a friend's story and pretended it happened to me",
        "thrown something out of the school bus window",
        "lied about staying after school and gone somewhere else",
        "hopped seats on the school bus",
        "forgotten the punchline of a joke",
        "sang a song out loud and messed up the lyrics",
        "walked in on someone in the bathroom",
        "had someone walk in on me in the bathroom",
        "sent a text to the wrong person",
        "tripped in public",
        "wet the bed after childhood",
        "attempted martial arts moves while by myself",
        "driven over a curb",
        "laughed so hard that I peed my pants",
        "called the wrong person, then pretended I meant to call them",
        "gone into the wrong restroom",
        "been so freaked out to be outside at night that I ran back in",
        "lost my swimwear bottoms",
        "broken a piece of furniture by sitting on it",
        "walked around with my zipper down",
        "bought a children's toy for myself, as an adult",
        "recorded video of myself singing or dancing",
        "gotten something stuck in my nose",
        "given myself a bad haircut",
        "been told I had bad breath",
        "screamed because of a bug",
        "practiced public speaking in the mirror",
        "had dandruff",
        "listened to Justin Bieber alone",
        "just looked at myself naked in the mirror",
        "pretended to wash my hands by turning the water on, just in case someone is listening",
        "smiled at someone when I realized I wasn't listening to what they were saying",
        "tried to impress a crush by seeming knowledgeable about things they liked",
        "refreshed over and over to see if I have any new messages",
        "pretended to text while I secretly take a million selfies",
        "been obsessed with One Direction",
        "imagined my life as a sitcom and thought about who would play me",
        "sat on a public toilet",
        "put gum under a table",
        "stepped barefoot in dog poop",
        "tasted dog or cat food",
        "had a baby spit up on me",
        "thrown up after seeing someone else throw up",
        "picked my nose and eaten it",
        "used someone else’s toothbrush",
        "worn someone else’s underwear",
        "used my hands as a tissue (out of necessity)",
        "crop dusted an elevator",
        "wiped my armpits with a towel instead of showering",
        "worn the same pair of underwear more than three days",
        "destroyed a public bathroom",
        "thrown up in my mouth and swallowed it",
        "used a public restroom that had no toilet paper",
        "worn perfume or cologne because I didn't have deodorant",
        "broken the \"five-second rule\"",
        "licked a coin",
        "worn the same jeans for a week without washing them",
        "changed a diaper",
        "gone more than a week without showering",
        "watched pimple-popping videos",
        "picked stuff out of my belly button",
        "used the bathroom and not washed my hands",
        "smelled clothing to see if they were too dirty to wear again",
        "had stinky feet",
        "let dirty dishes sit in the sink for over a week",
        "blown my nose and looked at what came out",
        "trimmed my toenails with my teeth",
        "turned underwear inside out to get more use out of it",
        "popped someone else's pimple",
        "peeled dead skin off my feet",
        "rubbed my skin to get the dead skin to roll up",
        "peed in the sink",
        "binge-eaten Little Debbie cakes",
        "eaten at Taco Bell more than three times in a week",
        "eaten a carton of ice cream by myself",
        "been to Arby's",
        "had a deep-fried candy bar",
        "eaten from someone else's plate when they weren't looking",
        "eaten something cold because I was too lazy to heat it up",
        "eaten pumpkin pie",
        "tried chicken and waffles",
        "tried anchovies",
        "dipped french fries into a milkshake",
        "eaten a salad",
        "bought myself a Happy Meal",
        "eaten more than three hot dogs at once",
        "tried a restaurant's food challenge",
        "tried to eat six Saltines in a minute",
        "put ice cubes in my milk and cereal",
        "drank pickle juice",
        "put candy on pizza",
        "tried pickles with peanut butter",
        "salted watermelon",
        "tried a banana and mayonnaise sandwich",
        "tried baby food",
        "eaten a full frozen pizza by myself",
        "made a gross smoothie",
        "tried counting how many licks it took to get to the center of a Tootsie Pop",
        "drank Surge",
        "eaten Pop Rocks",
        "eaten a Hot Pocket",
        "eaten alligator",
        "tried BBQ pork nachos",
        "cleaned out the fridge and found food over a year old",
        "cooked Thanksgiving dinner",
        "counted calories",
        "burnt my mouth willingly because I was too hungry to wait",
        "eaten Spam",
        "chewed with my mouth open",
        "used a baby spoon to eat ice cream so it would last longer",
        "eaten butter by itself",
        "eaten food while still standing with the fridge door open",
        "eaten a spoonful of frosting",
        "tried Taco Bell breakfast",
        "daydreamed about donuts",
        "eaten pizza for two or more meals in a day",
        "tried eggs with runny yolks",
        "been pulled over",
        "tried to flee the cops",
        "driven drunk",
        "been arrested",
        "used a fake ID",
        "snuck into a club",
        "smuggled food or candy into a movie theater",
        "stolen money from someone",
        "been in handcuffs",
        "spent time in detention",
        "snuck out of the house",
        "lied to my parents about where I was going",
        "crashed a party or wedding",
        "shoplifted from a store",
        "had to call the cops on someone",
        "gotten into a fistfight",
        "dated someone who was underage",
        "thrown something at a moving car",
        "called the cops on someone",
        "flirted with a police officer in hopes of not getting a ticket",
        "lied to a police officer",
        "prank called 911",
        "bought something stolen",
        "dine and dashed",
        "been drunk in public",
        "littered",
        "ran a red light",
        "broken in somewhere",
        "jumped a fence",
        "drank before turning 21",
        "returned an item I used or clothing I wore",
        "downloaded music illegally",
        "stolen Wi-Fi from an unsecured network",
        "spit out gum onto the ground",
        "jaywalked",
        "shared passwords to services so family or friends didn't have to pay",
        "been in violation of a school dress code",
        "made a fake social media account",
        "played poker at home for money",
        "driven without wearing a seatbelt",
        "used my cell phone while driving",
        "crossed state lines to buy better fireworks",
        "used medicine that was prescribed to me",
        "ridden a bike on the sidewalk",
        "passed a vehicle double yellow lines",
        "been drunk at a restaurant",
        "played beer pong",
        "tried to do a keg stand",
        "drank before I turned 21",
        "partied during spring break",
        "tried champagne",
        "said a toast",
        "drank more than three beers in a sitting",
        "drank alcohol in front of my parents",
        "fallen asleep and woken up somewhere else",
        "danced on a table or bar",
        "pretended to like a wine to look classier",
        "drank liquor straight from the bottle",
        "received a free drink",
        "texted someone I didn't mean to when I was tipsy",
        "left a drunk voicemail",
        "been the designated driver",
        "tried a craft beer",
        "toured a brewery",
        "tried moonshine",
        "watched The Hangover",
        "been hungover",
        "tried wine in a box",
        "purchased alcohol duty-free on a cruise",
        "broke up with someone while drunk",
        "found a cure for hangovers",
        "made up my own cocktail",
        "had a Jell-O shot",
        "made vodka gummy bears",
        "been to a wine tasting",
        "drank Crown Royal",
        "made an impulse purchase online while drunk",
        "drunkenly posted something on Facebook that I wished I hadn't",
        "lost count of how many drinks I had",
        "had to be carried to bed",
        "played \"Never Have I Ever\" before",
        "been the drunkest person at the party",
        "drank at a bar",
        "taken a shot with no hands",
        "had a stranger buy me a drink",
        "shotgunned a beer",
        "done a pub crawl",
        "drank a flaming shot",
        "done a body shot",
        "participated in a drinking competition",
        "been dumped by a girlfriend/boyfriend",
        "been white",
        "Been in an airplane",
        "played this game",
        "drank alcohol",
        "won a game of Monopoly",
        "taken an AP class",
        "cut down a Christmas tree",
        "had sex with a goat",
        "had my driver's license suspended or revoked",
        "had a warrant issued on me",
        "turned down a fat chick",
        "flown on an airplane",
        "been shot at",
        "cheated on somebody",
        "been to a wedding"
    };

    public static readonly List<string> NhieQuestionListAdult = new() {
        "heard someone else masturbating",
        "been on a blind date",
        "had a date with someone I met on an dating app",
        "made out with a stranger",
        "tried a cheesy pick-up line on someone",
        "had a cheesy pick-up line work on me",
        "sent someone a video of me giving head",
        "been on a double date with my parents",
        "tried skinny dipping",
        "made out with someone in a hot tub",
        "made a girl cum",
        "had a one-night stand",
        "had a crush on a friend's sibling",
        "had sex with someone more than 10 years older than me",
        "been to a drive-in movie",
        "been a friend with benefits",
        "skipped a movie to make out in the parking lot instead",
        "been playful with whipped cream",
        "looked at a dirty picture/video involving my ex",
        "dated more than one person at once",
        "bought lingerie",
        "been to an adult store",
        "watched a movie because I knew it had nudity",
        "played strip poker",
        "had sex in view of the public",
        "purposefully \"walked in\" on someone in the shower",
        "had sex with one of my teachers",
        "slipped someone my phone number",
        "whispered \"good girl\" in someone's ear",
        "stayed friends with benefits an ex",
        "had sex outside",
        "had a sex-related injury",
        "had breakfast in bed",
        "had a full-body massage",
        "adjusted my buttons on my shirt based on who's in the room",
        "fantasized about someone else while having sex",
        "sent someone a naughty videos of myself",
        "thought of having sex with me",
        "sucked a dick",
        "thrown up while giving head",
        "masturbated to a picture of someone in the room",
        "kissed someone of the same sex romantically",
        "sucked dick for weed",
        "used a condom",
        "watched porn with a partner",
        "had a threesome",
        "masturbated over three times in one day",
        "had sex in a submarine",
        "been fisted",
        "had anal sex",
        "masturbated on webcam for money",
        "tried using penis enlargement pills",
        "posted nudes of an ex online",
        "hit someone/been hit with a dick",
        "had sex with a porn star",
        "screamed your name",
        "faked an orgasm",
        "used someone else’s sex toy",
        "said the wrong name during sex",
        "been to an adult store"
    };
}