using System.Collections.Generic;

namespace HomeControl.Source.ViewModel.Games;

public static class WordList {
    public static List<string> PictionaryEasyList = new() {
        "Earth",
        "Christmas",
        "Mickey Mouse",
        "Above",
        "Alive",
        "Alligator",
        "Animal",
        "Ankle",
        "Answer",
        "Ants",
        "Apple",
        "Arm",
        "Awake",
        "Baby",
        "Backpack",
        "Bag",
        "Bald",
        "Ball",
        "Balloon",
        "Banana",
        "Bark",
        "Baseball",
        "Basketball",
        "Bat",
        "Bath",
        "Bathroom",
        "Beach",
        "Beak",
        "Bear",
        "Bed",
        "Bell",
        "Bench",
        "Bike",
        "Bird",
        "Blanket",
        "Blocks",
        "Boat",
        "Bone",
        "Book",
        "Bounce",
        "Bow",
        "Bowl",
        "Box",
        "Boy",
        "Bracelet",
        "Brake",
        "Branch",
        "Bread",
        "Breakfast",
        "Bridge",
        "Broken",
        "Broom",
        "Bubble",
        "Bug",
        "Bumblebee",
        "Bunk Bed",
        "Bunny",
        "Bus",
        "Butterfly",
        "Button",
        "Buzz",
        "Cafeteria",
        "Camera",
        "Candle",
        "Car",
        "Carrot",
        "Cash",
        "Cat",
        "Caterpillar",
        "Cave",
        "Chair",
        "Cheerleader",
        "Cheese",
        "Chef",
        "Cherry",
        "Chicken",
        "Chimney",
        "Circle",
        "Clock",
        "Cloud",
        "Coat",
        "Coin",
        "Comb",
        "Computer",
        "Cone",
        "Cookie",
        "Corn",
        "Cow",
        "Cowboy",
        "Crab",
        "Crack",
        "Crayon",
        "Cube",
        "Cup",
        "Cupcake",
        "Curl",
        "Dad",
        "Desk",
        "Diamond",
        "Dinner",
        "Dinosaur",
        "Doctor",
        "Dog",
        "Doll",
        "Door",
        "Down",
        "Dragon",
        "Draw",
        "Dream",
        "Drum",
        "Duck",
        "Ear",
        "Ears",
        "Egg",
        "Elephant",
        "Elevator",
        "Eye",
        "Eyes",
        "Face",
        "Fact",
        "Fairy",
        "Feather",
        "Feet",
        "Finger",
        "Fire",
        "Fire Hydrant",
        "First",
        "Fish",
        "Flag",
        "Float",
        "Flower",
        "Fly",
        "Fog",
        "Football",
        "Fork",
        "Fountain",
        "Front",
        "Frown",
        "Frying Pan",
        "Fur",
        "Ghost",
        "Giraffe",
        "Girl",
        "Glasses",
        "Grandchild",
        "Grapes",
        "Grass",
        "Green",
        "Gym",
        "Hail",
        "Hair",
        "Hamburger",
        "Hand",
        "Hat",
        "Head",
        "Heart",
        "Heavy",
        "Helicopter",
        "Hello",
        "Help",
        "Hide-and-seek",
        "High",
        "Hippo",
        "Homework",
        "Hoof",
        "Hook",
        "Horn",
        "House",
        "Hungry",
        "Ice Cream",
        "Ice Cream Cone",
        "Inchworm",
        "Iron",
        "Island",
        "Jacket",
        "Jail",
        "Jar",
        "Jellyfish",
        "Key",
        "Kick",
        "King",
        "Kite",
        "Kitten",
        "Knee",
        "Ladybug",
        "Lamp",
        "Laugh",
        "Leaf",
        "Leg",
        "Legs",
        "Lemon",
        "Library",
        "Light",
        "Light Bulb",
        "Line",
        "Lion",
        "Lips",
        "Lizard",
        "Lollipop",
        "Long",
        "Loud",
        "Love",
        "Mailman",
        "Makeup",
        "Man",
        "Milk",
        "Mitten",
        "Mom",
        "Monkey",
        "Monster",
        "Moon",
        "Motorcycle",
        "Mountain",
        "Mountains",
        "Mouse",
        "Mouth",
        "Movie",
        "Music",
        "Nail",
        "Nail Polish",
        "Neck",
        "Nephew",
        "Night",
        "Nose",
        "Ocean",
        "Octopus",
        "Oink",
        "Opposite",
        "Orange",
        "Oval",
        "Owl",
        "Page",
        "Paint",
        "Pantry",
        "Pants",
        "Peas",
        "Pen",
        "Pencil",
        "Person",
        "Picnic",
        "Picture",
        "Pie",
        "Pig",
        "Pillow",
        "Pizza",
        "Plant",
        "Play",
        "Poem",
        "Popsicle",
        "Prince",
        "Princess",
        "Purse",
        "Push",
        "Rabbit",
        "Rain",
        "Ranch",
        "Red",
        "Refrigerator",
        "Relax",
        "Restaurant",
        "Right",
        "Ring",
        "River",
        "Robot",
        "Rock",
        "Rocket",
        "Room",
        "Sailboat",
        "Sandcastle",
        "School",
        "School Bus",
        "Scientist",
        "Scissors",
        "Scooter",
        "Sea Turtle",
        "Seashell",
        "Seek",
        "Shadow",
        "Sheep",
        "Ship",
        "Shirt",
        "Shoe",
        "Shopping",
        "Shovel",
        "Sick",
        "Singer",
        "Sister",
        "Skateboard",
        "Slide",
        "Smile",
        "Smoke",
        "Snail",
        "Snake",
        "Sneeze",
        "Snowflake",
        "Snowman",
        "Sock",
        "Socks",
        "Spider",
        "Spider Web",
        "Spool",
        "Spoon",
        "Spy",
        "Square",
        "Stairs",
        "Stamp",
        "Star",
        "Starfish",
        "State",
        "Storm",
        "Street",
        "Strong",
        "Suitcase",
        "Sun",
        "Sunglasses",
        "Swimming Pool",
        "Swimsuit",
        "Swing",
        "Table",
        "Tail",
        "Teeth",
        "Telephone",
        "Thunder",
        "Tired",
        "Tissue",
        "Toast",
        "Toothbrush",
        "Towel",
        "Town",
        "Train",
        "Trash Can",
        "Tree",
        "Triangle",
        "Turtle",
        "Uncle",
        "Unicorn",
        "Up",
        "Vacation",
        "Vet",
        "Video Camera",
        "Wallet",
        "Watch",
        "Water",
        "Weak",
        "Whale",
        "Wheel",
        "Whisper",
        "Window",
        "Witch",
        "Wolf",
        "Woman",
        "Worm",
        "Yellow",
        "Zebra",
        "Zero",
        "Zigzag"
    };

    public static List<string> PictionaryMediumList = new() {
        "Friday",
        "Jupiter",
        "Segway",
        "Acne",
        "Aircraft",
        "Anvil",
        "Aquarium",
        "Art",
        "Artist",
        "Ask",
        "Aunt",
        "Baby",
        "Back",
        "Bag",
        "Bagel",
        "Bagpipe",
        "Banana Peel",
        "Banana",
        "Bandage",
        "Barn",
        "Baseboards",
        "Bat",
        "Batteries",
        "Battery",
        "Beach",
        "Beaver",
        "Birthday",
        "Birthday Cake",
        "Blackboard",
        "Blanket",
        "Blowfish",
        "Blue Jeans",
        "Blueprint",
        "Blush",
        "Bobsled",
        "Bowtie",
        "Box",
        "Braid",
        "Breakfast",
        "Brick",
        "Bruise",
        "Budget",
        "Bus",
        "Bushes",
        "Cage",
        "Calendar",
        "Campfire",
        "Canoe",
        "Cardboard",
        "Carpet",
        "Cartoon",
        "Cash",
        "Chalk",
        "Chameleon",
        "Chart",
        "Check",
        "Cheek",
        "Cheer",
        "Cheerleader",
        "Cheeseburger",
        "Children",
        "Chin",
        "Chips",
        "City",
        "Classroom",
        "Closed",
        "Coach",
        "Coat",
        "Cobra",
        "Cocoon",
        "Coil",
        "Coin",
        "Collar",
        "College",
        "Compass",
        "Computer",
        "Corn",
        "Corn Dog",
        "Cover",
        "Cowboy",
        "Coyote",
        "Cracker",
        "Crib",
        "Crumb",
        "Crust",
        "Cucumber",
        "Curb",
        "Curtains",
        "Curve",
        "Dad",
        "Daddy Longlegs",
        "Dance",
        "Deep",
        "Deer",
        "Delay",
        "Departure",
        "Desk",
        "Dew",
        "Dirt",
        "Dock",
        "Doctor",
        "Doghouse",
        "Dollar",
        "Door",
        "Doormat",
        "Drill",
        "Dump Truck",
        "Easel",
        "Eclipse",
        "Eel",
        "Electrical Outlet",
        "Electricity",
        "Elevator",
        "Elf",
        "Enter",
        "Equator",
        "Eraser",
        "Extension Cord",
        "Factory",
        "Family",
        "Faucet",
        "Fax",
        "Feast",
        "Ferry",
        "Firefighter",
        "Fishing Pole",
        "Fist",
        "Flagpole",
        "Flamingo",
        "Flood",
        "Foe",
        "Food",
        "Forehead",
        "Forest",
        "Free",
        "French Fries",
        "Front Porch",
        "Fruit",
        "Funny",
        "Gap",
        "Garbage Truck",
        "Gate",
        "Germ",
        "Giant",
        "Gingerbread Man",
        "Go",
        "Goat",
        "Goblin",
        "Goldfish",
        "Grandma",
        "Grape",
        "Growl",
        "Gum",
        "Hail",
        "Hair",
        "Hairbrush",
        "Half",
        "Hammer",
        "Happy",
        "Healthy",
        "Heel",
        "Hero",
        "Hip",
        "Home Movies",
        "Horse",
        "Hospital",
        "Hot Tub",
        "Hot-air Balloon",
        "Howl",
        "Hunter",
        "Hurricane",
        "Insect",
        "Ironing Board",
        "Island",
        "Jaw",
        "Jump",
        "Jungle",
        "Kayak",
        "Kettle",
        "Kiss",
        "Knot",
        "Latitude",
        "Lemon",
        "Lifejacket",
        "Lighthouse",
        "Lightsaber",
        "Liquid",
        "Locket",
        "Low",
        "Lung",
        "Magic Carpet",
        "Magnet",
        "Mail",
        "Mailman",
        "Map",
        "Marker",
        "Marshmallow",
        "Mine",
        "Minivan",
        "Mirror",
        "Mitten",
        "Monkey",
        "Morning",
        "Mountain Biking",
        "Mouth",
        "Movie Theater",
        "Mud",
        "Museum",
        "Mushroom",
        "Music",
        "Nail",
        "Napkin",
        "Narwhal",
        "Nature",
        "Needle",
        "Neon",
        "Net",
        "Newspaper",
        "Notepad",
        "Nurse",
        "Nut",
        "Oar",
        "Observe",
        "Oil",
        "Onion",
        "Open",
        "Page",
        "Paint",
        "Pajamas",
        "Panda",
        "Pantry",
        "Park",
        "Paw",
        "Peach",
        "Peanut",
        "Peck",
        "Pendulum",
        "Photograph",
        "Photographer",
        "Piano",
        "Pie",
        "Pigpen",
        "Pillowcase",
        "Pine Tree",
        "Pineapple",
        "Pinecone",
        "Ping Pong",
        "Pipe",
        "Piranha",
        "Pirate",
        "Plant",
        "Platypus",
        "Playground",
        "Pocket",
        "Pool",
        "Porch",
        "Pot",
        "Present",
        "Pretzel",
        "Princess",
        "Printer",
        "Prize",
        "Pulley",
        "Puppet",
        "Puzzle",
        "Quadruplets",
        "Radish",
        "Railroad",
        "Rainbow",
        "Rake",
        "Rat",
        "Rattle",
        "Recycle",
        "Refrigerator",
        "Reindeer",
        "Restaurant",
        "Rhinoceros",
        "Rib",
        "Ribbon",
        "Road Trip",
        "Robin",
        "Rocking Chair",
        "Roller Blading",
        "Room",
        "Root",
        "Rowboat",
        "Rug",
        "Run",
        "Salt and Pepper",
        "Sandpaper",
        "Sap",
        "Saxophone",
        "Scale",
        "Scar",
        "Scarf",
        "School",
        "Screwdriver",
        "Sea Turtle",
        "Seahorse",
        "Seal",
        "Seashell",
        "See",
        "Sense",
        "Shadow",
        "Shark",
        "Shed",
        "Shelf",
        "Shopping Cart",
        "Shovel",
        "Sidekick",
        "Skateboard",
        "Ski",
        "Skirt",
        "Sleeve",
        "Slide",
        "Slope",
        "Smog",
        "Snap",
        "Sneeze",
        "Snowball",
        "Snowboard",
        "Snowboarding",
        "Snowflake",
        "Snuggle",
        "Soccer",
        "Soil",
        "Solar System",
        "Spear",
        "Sponge",
        "Spool",
        "Spoon",
        "Squirrel",
        "Squirt Gun",
        "Stage",
        "Stain",
        "Start",
        "Stem",
        "Stepmom",
        "Stomach",
        "Stomp",
        "Stoplight",
        "Stork",
        "Storm",
        "Stove",
        "Strawberry",
        "String",
        "Stump",
        "Subway",
        "Suitcase",
        "Sunflower",
        "Sunglasses",
        "Surfboard",
        "Swimming Pool",
        "Swing",
        "Sword",
        "T-shirt",
        "Table",
        "Tadpole",
        "Tag",
        "Tar",
        "Taxi",
        "Team",
        "Teammate",
        "Teenager",
        "Tennis Shoes",
        "Tent",
        "Thief",
        "Third Plate",
        "Throat",
        "Throne",
        "Ticket",
        "Tightrope",
        "Time",
        "Timer",
        "Tip",
        "Toaster",
        "Toilet Paper",
        "Tongs",
        "Towel",
        "Tractor",
        "Trampoline",
        "Trap",
        "Treasure",
        "Truck",
        "Trumpet",
        "Tuba",
        "Tulip",
        "Unicycle",
        "Unite",
        "Usher",
        "Vegetable",
        "Verse",
        "Vest",
        "Video Camera",
        "Volunteer",
        "Want",
        "Waste",
        "Watchtower",
        "Waterfall",
        "Watering Can",
        "Wedge",
        "Week",
        "Weight",
        "Well",
        "Wind",
        "Window",
        "Windshield",
        "Wood",
        "Worm",
        "Wreck",
        "Wrist",
        "Writer",
        "Yo-yo",
        "Zebra",
        "Zoo"
    };

    public static List<string> PictionaryHardList = new() {
        "Bff",
        "Cd",
        "Heinz 57",
        "Internet",
        "Zen",
        "Abrasive",
        "Accounting",
        "Advertising",
        "Agenda",
        "Airport Security",
        "Airway",
        "Amusement Park",
        "Apathetic",
        "Applause",
        "Art Gallery",
        "Ashamed",
        "Athlete",
        "Avocado",
        "Baby-sitter",
        "Baguette",
        "Barber",
        "Bargain",
        "Baseboards",
        "Bedbug",
        "Beluga Whale",
        "Birthday",
        "Biscuit",
        "Blizzard",
        "Blossom",
        "Blueprint",
        "Blush",
        "Boa Constrictor",
        "Bonnet",
        "Bookend",
        "Booth",
        "Brand",
        "Bruise",
        "Buddy",
        "Captain",
        "Carat",
        "Cardboard",
        "Cargo",
        "Carnival",
        "Cartoon",
        "Catalog",
        "Ceiling Fan",
        "Cellar",
        "Chameleon",
        "Character",
        "Cheat",
        "Cheerleader",
        "Chisel",
        "Clamp",
        "Classroom",
        "Clay",
        "Clique",
        "Cloak",
        "Clown",
        "Coastline",
        "Coil",
        "Comfy",
        "Commercial",
        "Compare",
        "Competition",
        "Connection",
        "Costume",
        "Cot",
        "Country",
        "Cowboy",
        "Crate",
        "Cream",
        "Crime",
        "Crop Duster",
        "Crow's Nest",
        "Crust",
        "Cubicle",
        "Cuckoo Clock",
        "Cupola",
        "Cushion",
        "Customer",
        "Dance",
        "Date",
        "Dawn",
        "Dead End",
        "Degree",
        "Deliver",
        "Dentist",
        "Dew",
        "Dimple",
        "Disc Jockey",
        "Distance",
        "Diver",
        "Divine",
        "Dizzy",
        "Dodgeball",
        "Dorsal",
        "Drain",
        "Dream",
        "Dress Shirt",
        "Drip",
        "Dripping",
        "Earache",
        "Earthquake",
        "Edit",
        "Eighteen-wheeler",
        "Electrical Outlet",
        "Elf",
        "Elope",
        "Environment",
        "Eraser",
        "Exercise",
        "Fade",
        "Fast Food",
        "Fiddle",
        "Fireman Pole",
        "Fireside",
        "First Class",
        "Fizz",
        "Flannel",
        "Flavor",
        "Flu",
        "Flush",
        "Foam",
        "Forever",
        "Fortress",
        "Fourth Down",
        "Freshman",
        "Front",
        "Gas Station",
        "Geologist",
        "Germ",
        "Geyser",
        "Ginger",
        "Glue Stick",
        "Goalkeeper",
        "Goblin",
        "Gold Medal",
        "Government",
        "Gown",
        "Grandpa",
        "Grasslands",
        "Great-grandfather",
        "Grocery Store",
        "Guile",
        "Hairspray",
        "Hand Soap",
        "Hang Glider",
        "Headache",
        "Hearty",
        "Heater",
        "Hermit Crab",
        "Hipster",
        "Hole in One",
        "Hospital",
        "Hot Tub",
        "Houseboat",
        "Household",
        "Human",
        "Humidifier",
        "Humidity",
        "Hurdle",
        "Husband",
        "Hut",
        "Hydrogen",
        "Icicle",
        "Important",
        "Injury",
        "Inspect",
        "Interception",
        "Irritated",
        "Ivy",
        "Jade",
        "Jaw",
        "Jazz",
        "Jog",
        "Judge",
        "Juggle",
        "Jungle",
        "Junk",
        "Knight",
        "Lace",
        "Laminate",
        "Landlord",
        "Lap",
        "Laser",
        "Last",
        "Laundry Detergent",
        "Leak",
        "Learn",
        "Lend",
        "Letter Opener",
        "Light-year",
        "Living Room",
        "Loveseat",
        "Lullaby",
        "Lumberyard",
        "Lunch Tray",
        "Lung",
        "Macaroni",
        "Major League",
        "Manatee",
        "Mascot",
        "Mast",
        "Mayor",
        "Molar",
        "Movie",
        "Multiplication",
        "Musician",
        "Nanny",
        "Nap",
        "New",
        "Nightmare",
        "Oar",
        "Opponent",
        "Orbit",
        "Organ",
        "Owner",
        "Pail",
        "Pain",
        "Parade",
        "Parent",
        "Password",
        "Pawn",
        "Payment",
        "Pest",
        "Pharaoh",
        "Phonemics",
        "Pickup Truck",
        "Picture Frame",
        "Pigpen",
        "Pilot",
        "Pizza Sauce",
        "Plaid",
        "Plank",
        "Plantation",
        "Plow",
        "Plumber",
        "Pocket",
        "Poison",
        "Postcard",
        "Prey",
        "Prime Meridian",
        "Printer Ink",
        "Produce",
        "Professor",
        "Propose",
        "Publisher",
        "Punk",
        "Puppet",
        "Purge",
        "Purpose",
        "Putty",
        "Puzzle Piece",
        "Quicksand",
        "Quit",
        "Ratchet",
        "Reason",
        "Receipt",
        "Recess",
        "Record",
        "Reimbursement",
        "Religion",
        "Replace",
        "Research",
        "Resident",
        "Retail",
        "Reveal",
        "Riddle",
        "Rim",
        "Ringleader",
        "Roller Coaster",
        "Roommate",
        "Ruby",
        "Rut",
        "S'mores",
        "Saddle",
        "Safe",
        "Salmon",
        "Sash",
        "Scalawag",
        "Scar Tissue",
        "School",
        "Scoundrel",
        "Scuff Mark",
        "Scurvy",
        "Season",
        "Self",
        "Shack",
        "Shampoo",
        "Sheep Dog",
        "Shower Curtain",
        "Shrew",
        "Shrink Ray",
        "Signal",
        "Sip",
        "Skating Rink",
        "Ski Goggles",
        "Ski Lift",
        "Sled",
        "Smoldering",
        "Snooze",
        "Snore",
        "Snow Shoe",
        "Snowstorm",
        "Somersault",
        "Sow's Ear",
        "Space Shuttle",
        "Speakers",
        "Spite",
        "Spoil",
        "Sponge",
        "Sports Car",
        "Squeegee",
        "Stadium",
        "Stage",
        "Station Wagon",
        "Sticky Note",
        "Stockbroker",
        "Stow",
        "Stutter",
        "Sugar",
        "Sun Block",
        "Sunburn",
        "Surround",
        "Sushi",
        "Swamp",
        "Swarm",
        "Sweater",
        "Sweater Vest",
        "Swing Dancing",
        "Swirl",
        "Sword Swallower",
        "Tablespoon",
        "Taxes",
        "Taxi",
        "Taxidermist",
        "Team",
        "Tearful",
        "Teleconference",
        "Telephone Booth",
        "Tendency",
        "Terrify",
        "Testify",
        "Thaw",
        "Theorize",
        "Thief",
        "Think",
        "Through",
        "Ticket",
        "Tilt",
        "Time Machine",
        "Tin",
        "Tinting",
        "Tip",
        "Tiptoe",
        "Toddler",
        "Tow Truck",
        "Traffic Jam",
        "Trapped",
        "Trip",
        "Trombone",
        "Truck Stop",
        "Tugboat",
        "Turtleneck",
        "University",
        "Urgent",
        "Vacation",
        "Vanish",
        "Vein",
        "Vessel",
        "Violent",
        "Wag",
        "Water Buffalo",
        "Water Cycle",
        "Waver",
        "Wax",
        "Weather",
        "Wedding Cake",
        "Welder",
        "Whatever",
        "Wheelie",
        "Whisk",
        "Whole Milk",
        "Wind",
        "Wish",
        "Wool",
        "Wooly Mammoth",
        "World",
        "Wrap",
        "Wreath",
        "Yacht",
        "Yak",
        "Yard",
        "Yardstick",
        "Yodel",
        "Zigzag",
        "Zipper",
        "Zoom"
    };

    public static List<string> PictionaryAdultList = new() {
        "69",
        "Baby Maker",
        "Bad Ass",
        "Blow Job",
        "Bondage",
        "Booty Call",
        "Cock",
        "Cow Girl",
        "Crack Head",
        "Deepthroat",
        "Doggy Style",
        "Gold Digger",
        "Grenade",
        "Happy Trail",
        "Hooker",
        "Lap Dance",
        "One Night Stand",
        "Second Base",
        "Sexting",
        "Swingers",
        "Threesome",
        "Twerk",
        "Vibrator"
    };
}