namespace HomeControl.Source.Json;

public class JsonSettings {
    public string UserAgent { get; set; }
    public string User1Name { get; set; }
    public string User2Name { get; set; }
    public string User3Name { get; set; }
    public string User4Name { get; set; }
    public string User5Name { get; set; }
    public string User1NameLegal { get; set; }
    public string User2NameLegal { get; set; }
    public string User3NameLegal { get; set; }
    public string User4NameLegal { get; set; }
    public string User5NameLegal { get; set; }
    public string User1Phone1 { get; set; }
    public string User1Phone2 { get; set; }
    public string User2Phone1 { get; set; }
    public string User2Phone2 { get; set; }
    public string PetNames { get; set; }
    public string Neighbor1Location { get; set; }
    public string Neighbor1Name { get; set; }
    public string Neighbor1Phone1 { get; set; }
    public string Neighbor1Phone2 { get; set; }
    public string Neighbor2Location { get; set; }
    public string Neighbor2Name { get; set; }
    public string Neighbor2Phone1 { get; set; }
    public string Neighbor2Phone2 { get; set; }
    public string AddressLine1 { get; set; }
    public string AddressLine2 { get; set; }
    public string FireExtinguisherLocation { get; set; }
    public string HospitalAddressLine1 { get; set; }
    public string HospitalAddressLine2 { get; set; }
    public string WifiGuestName { get; set; }
    public string WifiGuestPassword { get; set; }
    public string WifiPrivateName { get; set; }
    public string WifiPrivatePassword { get; set; }
    public string PoliceName { get; set; }
    public string PolicePhone { get; set; }
    public string EmergencyContact1Name { get; set; }
    public string EmergencyContact1Phone1 { get; set; }
    public string EmergencyContact1Phone2 { get; set; }
    public string EmergencyContact2Name { get; set; }
    public string EmergencyContact2Phone1 { get; set; }
    public string EmergencyContact2Phone2 { get; set; }
    public string AlarmCode { get; set; }
    public string ComPort { get; set; }
    public bool useMetricUnits { get; set; }
    public bool useEasterEggs { get; set; }
    public bool DebugMode { get; set; }
    public string TrashDay { get; set; }
    public double WeatherLat { get; set; }
    public double WeatherLon { get; set; }
    public int GridX { get; set; }
    public int GridY { get; set; }
    public string WeatherLocation { get; set; }
    public string GridId { get; set; }
    public string FinanceBlock1 { get; set; }
    public string FinanceBlock2 { get; set; }
    public string FinanceBlock3 { get; set; }
    public string FinanceBlock4 { get; set; }
    public string FinanceBlock5 { get; set; }
    public string FinanceBlock6 { get; set; }
    public string FinanceBlock7 { get; set; }
    public string FinanceBlock8 { get; set; }
    public string FinanceBlock9 { get; set; }
    public bool IsOff { get; set; }
    public bool IsClient { get; set; }
    public bool IsServer { get; set; }
    public string IpAddress { get; set; }
    public string Port { get; set; }
}